name: Delete old workflow runs

on: [push]

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: delete workflow runs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 86400                           # remove all workflow runs older than 1 day
        env:
          GITHUB_TOKEN: ${{ github.token }}
